### ISSUE TITLE
Max post date + Min post date are confusing and with weird default

### ISSUE THREAD

**Issue by metalwarrior665** [pocesar/actor-facebook-scraper#20]
1. I'm not sure how to set these up properly. I would instead choose more clear field names (just the human names so we don't break). Like "Scrape posts from date", "Scrape posts to date" or something like that (we can brainstorm).

2. The default value for both is '2020-01-01' which means it scrapes only posts from a single day? I would keep "Scrape posts to date" empty so it scrapes from now and use this value for "Scrape posts from date"

**Comment by pocesar** [comment]
the logic is confusing a lot. the max post date needs to "include" the min post date, in the past. since the posts are ordered in a descending manner, it always start with the newest to oldest. when you set only the max post, it will go up (or down) to that specific date. setting it to 2020-11-01 will get 2020-11-04 down to that date. 
when using minimum post date, it will start "counting" posts from the date you specify, so if you set 2020-11-01, the max post date necessarily needs to be lower, otherwise it won't be able to intersect the dates, taking that today is 2020-11-04, will start at 2020-11-01 down to max post date of 2020-10-31 for example, so it will get only 1 day (if any)

**Comment by pocesar** [comment]
this should be done
